# Generated by Django 5.2.3 on 2025-07-10 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('consulta', 'Consulta General'), ('cirugia', 'Cirugía'), ('laboratorio', 'Laboratorio'), ('farmacia', 'Farmacia'), ('peluqueria', 'Peluquería'), ('hospitalizacion', 'Hospitalización'), ('emergencia', 'Emergencia')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_estimada', models.IntegerField(help_text='Duración en minutos')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('otro', 'Otro')], max_length=10)),
                ('raza', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='programada', max_length=15)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('motivo', models.TextField(help_text='Motivo de la consulta')),
                ('observaciones', models.TextField(blank=True)),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='app.mascota')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicio')),
            ],
            options={
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
